apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.18.0  # Use the latest stable version
    helm:
      values: |
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: cert-manager
          ingress:
            hosts:
              core: harbor.kube.dungeonmomo.cc
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
        externalURL: https://harbor.kube.dungeonmomo.cc
        persistence:
          enabled: true
          resource:
            storage:
              data: 50Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true