apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://tailscale.github.io/helm-charts'
    chart: tailscale-operator
    targetRevision: 1.76.0
    helm:
      values: |
        oauth:
          secretName: "tailscale-auth"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true